name: Production deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: https://tsuyo.jfrog.io/artifactory/api/npm/ga/
          token: ${{ secrets.NPM_TOKEN }}
          
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      # - uses: actions/upload-artifact@master
      #   with:
      #     name: webpack artifacts
      #     path: public/
      - uses: jfrog/setup-jfrog-cli@v1
      - run: jfrog --version

  # deploy:
  #   name: Deploy Node.js app to AWS
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: Download built artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: webpack artifacts
  #         path: public

  #     - name: Deploy to AWS
  #       uses:  github/deploy-nodejs@master
  #       env:
  #         AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  #         AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

  # Build-and-Push-Docker-Image:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   name: Docker Build, Tag, Push
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Download built artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: webpack artifacts
  #         path: public

  #     - name: Build, Tag, Push
  #       uses: mattdavis0351/actions/docker-gpr@v1
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #         image-name: tsuyo-aws-ttt
